services:
  # service backend
  backend:
    build: ./backend
    # ports:
    #   - 4000:4000
    volumes:
      - ./backend/src:/app/src
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      # - POSTGRES_HOST=db
      # - POSTGRES_PORT=5432
      # - POSTGRES_USER=postgres
      # - POSTGRES_PASSWORD=password
      # - POSTGRES_DB=the_good_corner
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: 'curl --fail --request POST --header ''content-type: application/json'' --url ''http://localhost:4000'' --data ''{"query":"query { __typename }"}'' || exit 1'
      interval: 1s
      timeout: 2s
      retries: 100
    env_file:
      - .env # On utilise directement le fichier .env pour éviter de répéter les variables

  # service front end
  frontend:
    build: ./frontend
    # ports:
    #   - 5173:5173
    volumes:
      - ./frontend/src:/app/src
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --request GET --url 'http://localhost:5173' || exit 1"
      interval: 1s
      timeout: 2s
      retries: 100

  # service db
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: the_good_corner
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # service adminer
  adminer:
    image: adminer
    restart: always
    # ports:
    #   - 8080:8080

  # service api_gateway
  api_gateway:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_healthy
    ports:
      - 7000:80

volumes:
  postgres_data:
