GET http://localhost:3000/tags

###
POST http://localhost:3000/tags
Content-Type: application/json

{
    "name": "en cours"
}

###
PUT http://localhost:3000/tags/2
Content-Type: application/json

{
    "name": "coucou"
}

###
DELETE http://localhost:3000/tags/6
